Prepare for teaching some methods to not require an initrd
Replace the global check for the availability of an initrd by a check
per method. This way each method can be changed individually to support
a kernel without initrd.

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -753,7 +753,11 @@ ifile="/boot/initrd.img-$kvers"
 desc="kernel $kvers"
 idesc="ramdisk $kvers"
 
-if [ ! -e $kfile ] || [ ! -e $ifile ]; then
+if [ ! -e "$ifile" ]; then
+	ifile=
+fi
+
+if [ ! -e $kfile ]; then
 	# installation-report #781742 included:
 	#     Can't find /boot/vmlinuz-[...] or /boot/initrd.img-[...]
 	#
@@ -765,10 +769,10 @@ if [ ! -e $kfile ] || [ ! -e $ifile ]; then
 		ls -l $kfile*
 		ls -l $ifile*
 	) >> /tmp/flash-kernel-no-kernel-error.log 2>&1 || :
-	error "Can't find $kfile or $ifile (see /tmp/flash-kernel-no-kernel-error.log)"
+	error "Can't find $kfile (see /tmp/flash-kernel-no-kernel-error.log)"
 fi
 kfilesize=$(stat -c '%s' "$kfile")
-ifilesize=$(stat -c '%s' "$ifile")
+[ -z "$ifile" ] || ifilesize=$(stat -c '%s' "$ifile")
 
 if [ -L "$kfile" ]; then
 	kfile=$(readlink -e "$kfile")
@@ -880,6 +884,7 @@ tmpdir="$(mktemp -dt "$self.XXXXXXXX")"
 
 case "$method" in
 	"android")
+		[ -n "$ifile" ] || error "Initrd required for android method"
 		part=""
 		largest_size="-1"
 		for p in "$android_boot_device"*[0-9]; do
@@ -898,6 +903,7 @@ case "$method" in
 		android_flash "$part"
 	;;
 	"bootspec")
+		[ -n "$ifile" ] || error "Initrd required for bootspec method"
 		{
 			printf "title\t\tDebian\n"
 			printf "version\t\t$(cat /etc/debian_version) ($desc)\n"
@@ -913,6 +919,7 @@ case "$method" in
 		mv "$tmpdir/debian.conf" /loader/entries/debian.conf
 	;;
 	"generic")
+		[ -n "$ifile" ] || error "Initrd required for generic method"
 		kernel="$kfile"
 		initrd="$ifile"
 		if [ "$dtb_append" = "yes" ]; then
@@ -1014,11 +1021,13 @@ case "$method" in
 		fi
 	;;
 	"symlink")
+		[ -n "$ifile" ] || error "Initrd required for symlink method"
 		rm -f /boot/initrd /boot/zImage
 		ln -s "$(basename "$ifile")" /boot/initrd
 		gen_kernel "$kfile" "/boot/zImage" "$machine_id"
 	;;
 	"multi")
+		[ -n "$ifile" ] || error "Initrd required for multi method"
 		gen_kernel "$kfile" "$tmpdir/kernel" ""
 		# Hack to work around a bug in some U-Boot versions:
 		if [ $(($(stat -c '%s' "$tmpdir/kernel") % 4)) -eq 0 ]; then
@@ -1030,11 +1039,13 @@ case "$method" in
 		backup_and_install "$tmpdir/uImage" "$boot_multi_path"
 	;;
 	"redboot")
+		[ -n "$ifile" ] || error "Initrd required for redboot method"
 		flash_kernel "$kfile" "$kmtd" "$machine_id"
 		pad=$(($imtdsize - $ifilesize))
 		flash_initrd "$ifile" "$imtd" $pad
 	;;
 	"slug")
+		[ -n "$ifile" ] || error "Initrd required for slug method"
 		case "$(dpkg --print-architecture)" in
 			arm|armel)
 				little_endian=1
